name: Deploy to Kubernetes Cluster

on:
  push:
    tags:
      - v1.*
jobs:
  export-var:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.version }}
    steps:
      - run: echo "version=${{ github.ref_name }}" | sed 's/=v/=/' >> $GITHUB_ENV

  setup:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y apt-transport-https ca-certificates curl
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: sudo mv ./kubectl /usr/local/bin/kubectl

  build:
    name: Build
    needs: export-var
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kawaiiislands/kawaii-reward-merkle:${{ needs.export-var.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    needs: [ build, setup, export-var ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
      - run: sed -i 's/\$DOCKER_IMAGE_VERSION/${{ needs.export-var.outputs.version }}/' k8s/prod.yaml
      - name: Deploy app
        run: kubectl --kubeconfig=kubeconfig.yaml apply -f k8s/prod.yaml
